(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var F4=function(a){a.X("cardstatechange",a.wi()&&a.Zl()?1:0)},G4=function(a,b){var c=g.Oa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},N0a=function(a){var b=g.El(a);
a=g.Hl(a);return new g.tl(b.x,b.y,a.width,a.height)},O0a=function(a){return Math.pow(a,3)},P0a=function(a){return 3*a*a-2*a*a*a},J4=function(a){a=g.Ra(a);
delete H4[a];g.Bf(H4)&&I4&&I4.stop()},R0a=function(){I4||(I4=new g.Un(function(){Q0a()},20));
var a=I4;a.isActive()||a.start()},Q0a=function(){var a=g.Ua();
g.of(H4,function(b){S0a(b,a)});
g.Bf(H4)||R0a()},K4=function(a,b,c,d){g.no.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.N=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},S0a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;T0a(a,a.progress);1==a.progress?(a.j=0,J4(a),a.onFinish(),a.Iz()):a.Mc()&&a.hF()},T0a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.N[c]-a.u[c])*b+a.u[c]},U0a=function(a,b){g.hf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},L4=function(a,b,c,d,e){K4.call(this,b,c,d,e);
this.element=a},V0a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
L4.call(this,a,b,c,d,e)},M4=function(a){g.K.call(this);
this.u=a||window;this.j=[]},N4=function(a){return a.baseUrl||null},O4=function(a,b){return g.vm(g.Ok(a,b),function(c){return!!c})},W0a=function(a,b,c){function d(ca){var R=ca.hovercardButton;
if(!R)return null;R=R.subscribeButtonRenderer;if(!R)return null;var na=f(R.unsubscribedButtonText),sa=f(R.subscribedButtonText);if(R.subscribed){var za=f(R.subscriberCountWithUnsubscribeText);var wa=f(R.subscriberCountText)}else za=f(R.subscriberCountText),wa=f(R.subscriberCountWithSubscribeText);var ta=null;if(ca.signinEndpoint){ta=G4(ca,"signinEndpoint","webNavigationEndpointData","url");if(!ta){var Na,La,qa;ta=null==(Na=R.signInEndpoint)?void 0:null==(La=Na.commandMetadata)?void 0:null==(qa=La.webCommandMetadata)?
void 0:qa.url}if(!ta)return null}return na&&(sa||ta)?{subscribed:R.subscribed,subscribeText:na,subscribeCount:za,unsubscribeText:sa,unsubscribeCount:wa,enabled:R.enabled,signinUrl:ta,classic:ca.useClassicSubscribeButton}:null}
function e(ca){if(ca){var R=[],na=ca.videoId;na&&R.push("v="+na);(na=ca.playlistId)&&R.push("list="+na);(ca=ca.startTimeSeconds)&&R.push("t="+ca);return"/watch?"+R.join("&")}}
function f(ca){if(!ca)return null;var R=ca.simpleText;return R?R:ca.runs?g.Ok(ca.runs,function(na){return na.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,v=null,w=null,y=null,A=!1,B=null,E=null,G=null,H=null,I=null,O=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(O=l.watchEndpoint,m=e(O)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,v=f(p.text),p="LIVE"===p.style):v=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(O=l.watchEndpoint,m=e(O)),n=!1,q=a,w=f(b.playlistLength);
else if("CHANNEL"===h){if(A=G4(l,"browseEndpoint","browseId"))y=A,m="/channel/"+y;n=!1;q="new";(A=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((G=G4(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=G4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=G4(b,"title","accessibility","accessibilityData","label");var L=b.endpoint?b.endpoint.clickTrackingParams:
null,P="";if(b.metadata){var S=f(b.metadata);S&&(P=S)}return{id:"element-"+c,type:h,title:f(b.title),metadata:P,callToAction:f(b.callToAction),lO:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:v,isLiveVideo:p,playlistLength:w,channelId:y,subscribeButton:B,subscribersText:E,isSubscribe:A,targetUrl:m||null,vZ:n,sessionData:L?{itct:L}:null,N4:q,Kx:a?a:
null,isPlaceholder:b.isPlaceholder,impressionUrls:O4(b.impressionUrls||[],N4),gZ:O4(b.hovercardShowUrls||[],N4),clickUrls:O4(l.loggingUrls||[],N4),visualElement:g.mz(b.trackingParams),productPrice:H,additionalFeesText:I,watchEndpoint:O||null}},X0a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:O4(a.impressionUrls||[],N4),elements:O4(a.elements||[],function(d,e){return W0a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.mz(a.trackingParams));return c},Y0a=function(a){g.XN.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.V=!0;this.I=0;a=a.R();this.N=g.MF(a)||g.QF(a);this.W=a.experiments.fb("web_rounded_thumbnails");this.events=new g.SD(this);g.M(this,this.events);this.events.P(this.player,g.mA("creatorendscreen"),this.onCueRangeEnter);this.events.P(this.player,g.nA("creatorendscreen"),this.onCueRangeExit);this.events.P(this.player,"resize",this.xb);this.events.P(window,"focus",this.N2);this.load();var b=g.mh("STYLE");(g.bh("HEAD")[0]||
document.body).appendChild(b);g.ff(this,function(){g.qh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Z0a=function(a){return a.player.getVideoData().C?"current":a.N?"new":"current"},P4=function(a){return"creator-endscreen-editor"===a.player.R().playerStyle},$0a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=X0a(f,Z0a(a))));Q4(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.rs;d&&(c.postParams={ad_tracking:d});if(b=g.OBa(b))if(b=g.mg(b),b=g.lg(b))a.B=g.vu(b,c)},Q4=function(a,b,c){c=void 0===c?!0:c;
a.player.zf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&a1a(a);c=[];d=new g.kA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.R().isMobile||(a.u=new g.X({F:"div",L:"ytp-ce-shadow"}),g.vN(a.player,a.u.element,4),a.C=new g.EL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=b1a(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.vN(a.player,f.element,4);var h=new g.kA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);c1a(a,
f,e)}else g.jz(new g.Iv("buildEndscreenElement null",e))}a.player.le(c);a.xb()}},a1a=function(a){var b=g.sz(),c=g.tz();
c&&b&&a.endscreen.visualElement&&g.xz(void 0,c,b,[a.endscreen.visualElement])},b1a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ca:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.Kx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:R4(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:S4(a,b.targetUrl),tabindex:"-1"},S:[{F:"div",Ca:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.ro(b.title||"")},Z:b.title},{F:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Z:b.videoDuration||void 0}]}]};c=new g.X(a);break;case "PLAYLIST":a={F:"div",Ca:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.Kx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:R4(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:S4(a,b.targetUrl),tabindex:"-1"},S:[{F:"div",Ca:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.ro(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-playlist-count",
S:[{F:"div",L:"ytp-ce-playlist-icon"},{F:"div",L:"ytp-ce-playlist-count-text",Z:b.playlistLength||void 0}]}]}]};c=new g.X(a);break;case "CHANNEL":c={F:"div",Ca:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.Kx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",S:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
S:[{F:"div",L:"ytp-ce-expanding-overlay-body",S:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{F:"a",Ca:["ytp-ce-channel-title","ytp-ce-link"],T:{href:S4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.ro(b.title||"")},Z:b.title},b.subscribeButton?{F:"div",L:"ytp-ce-subscribe-container",S:[{F:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",L:"ytp-ce-channel-subscribers-text",Z:b.subscribersText}:"",b.metadata?{F:"div",Ca:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Z:b.metadata}:""]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:R4(b)}]};c=new g.X(c);var d=g.ch(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.bo(d,"ytp-ce-subscribe-button");if(a.player.R().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.$O(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ca:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.Kx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",S:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
S:[{F:"div",L:"ytp-ce-expanding-overlay-body",S:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{F:"div",L:"ytp-ce-website-title",T:{dir:g.ro(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-website-metadata",Z:b.metadata},{F:"a",Ca:["ytp-ce-website-goto","ytp-ce-link"],T:{href:S4(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:R4(b)},{F:"div",L:"ytp-ce-expanding-icon",T:d1a(b.iconUrl)}]};c=new g.X(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",L:"ytp-ce-merchandise-price-container",S:[{F:"div",L:"ytp-ce-merchandise-price",Z:b.productPrice}]},b.additionalFeesText&&c.S.push({F:"div",L:"ytp-ce-merchandise-additional-fees",Z:b.additionalFeesText})),a={F:"div",Ca:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.Kx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",S:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},
{F:"div",L:"ytp-ce-expanding-overlay-content",S:[{F:"div",L:"ytp-ce-expanding-overlay-body",S:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{F:"div",L:"ytp-ce-merchandise-title",T:{dir:g.ro(b.title||"")},Z:b.title},c,{F:"div",L:"ytp-ce-merchandise-metadata",Z:b.metadata},{F:"a",Ca:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:S4(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:R4(b)},{F:"div",L:"ytp-ce-merchandise-invideo-cta-container",
S:[{F:"div",L:"ytp-ce-merchandise-invideo-cta",Z:b.callToAction||void 0}]}]},c=new g.X(a)}b.isPlaceholder&&g.bo(c.element,"ytp-ce-placeholder");return c},R4=function(a){if(a.lO)var b=a.lO.thumbnails;
return d1a(b?b[b.length-1].url:null)},d1a=function(a){return a?{style:"background-image: url("+a+")"}:{}},c1a=function(a,b,c){function d(m){m&&(b.Na("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.P(m,"focus",f),b.P(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.bo(b.element,"ytp-ce-force-expand"),T4(a,c.id,!0)):(g.eo(b.element,"ytp-ce-force-expand"),g.eo(b.element,"ytp-ce-element-hover"),T4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Na("mouseenter",function(){e1a(a,b,c)});
b.Na("mouseleave",function(){f1a(a,b,c)});
a.player.R().isMobile||b.Na("click",function(){g.bo(b.element,"ytp-ce-element-hover")});
b.Na("click",function(m){g1a(a,c,m)});
b.Na("keypress",function(m){g1a(a,c,m)});
b.Na("focus",function(){e1a(a,b,c)});
b.Na("blur",function(){f1a(a,b,c)});
b.Na("touchstart",function(){e1a(a,b,c)});
var l=g.eh("ytp-ce-expanding-overlay-hider",b.element);l&&b.P(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.eo(b.element,"ytp-ce-element-hover");g.eo(b.element,"ytp-ce-force-expand")});
b.Na("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.eh("ytp-sb-subscribe",b.element));d(g.eh("ytp-sb-unsubscribe",b.element));b.Na("focus",f);b.Na("blur",h)},g1a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.ao(d,"ytp-ce-element");){g.ao(d,"subscribe-label")&&h1a(a,b);
if(g.ao(d,"ytp-ce-channel-subscribe"))return;d=g.rh(d)}if(!d||g.ao(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])f1a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.N4)h1a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.mg(S4(a,b.targetUrl)),g.dM(g.lg(c),void 0,b.sessionData);else{var e=g.fG(a.player.R())||a.player.getVideoData().C,f=function(){var h=S4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.gu(h);e&&n&&(n.v||
n.list)?a.player.Cl(n.v,l,n.list,!1,void 0,m||void 0):g.cM(h,l)};
h1a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},S4=function(a,b){a=a.player.R();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.pG(a)+b}else return"";return b},e1a=function(a,b,c){g.ao(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.bo(b.element,"ytp-ce-element-hover"):a.player.R().isMobile?(new g.Un(function(){g.bo(b.element,"ytp-ce-element-hover")},200)).start():g.bo(b.element,"ytp-ce-element-hover"),U4(a,c.gZ),T4(a,c.id,!0))},f1a=function(a,b,c){g.eo(b.element,"ytp-ce-element-hover");
g.eo(b.element,"ytp-ce-force-expand");T4(a,c.id,!1)},T4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.j[e].element,"ytp-ce-element-shadow-show",c)},U4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||P4(a))c&&c();else{b=i1a(a,b);var e=0,f=!1,h=new g.Un(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Ow(b[a],d)}},h1a=function(a,b,c){U4(a,b.clickUrls,c);
(a=g.tz())&&b.vZ&&g.Dz(a,b.visualElement)},i1a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(j1a(b[d],c));return a},j1a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},k1a=function(a){return"string"===typeof a?a:""},V4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},l1a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},W4=function(a){return a.value?a.value:null},X4=function(a){if(!a)return null;
var b=g.mg(k1a(a.value));b=g.lg(b);if(!b)return null;var c=V4(a.target,m1a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new l1a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},n1a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},q1a=function(a){if(!a)return null;
var b=V4(a.type,o1a),c=V4(a.trigger,p1a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=X4(a?a:null);return b?new n1a(b,c,a):null},r1a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},s1a=function(a,b){return g.Ub(a.action,b)},t1a=function(a,b){this.context=a;
this.j=b},u1a=function(a){return a.customMessage?Y4("div","iv-card-message",a.customMessage):""},Z4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",L:"iv-card-image",T:{style:a},S:c}},v1a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Y4("li","",c.value));return{F:"ul",L:"iv-card-meta-info",S:b}},Y4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.ro(c);return{F:a,T:b,Z:c}},w1a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Tx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Tx+");");c.dir=g.ro(a.customMessage);var d=[{F:"span",Z:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",L:"iv-card-link-icon"}));return{F:"div",Ca:b,T:c,S:d}},$4=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},x1a=function(a,b){this.merchant=a;
this.price=b},y1a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},z1a=function(a,b){return b?b:y1a(a)?"current":"new"},a5=function(a,b){g.K.call(this);
var c=this;this.element=a;this.context=b;this.yb=!1;this.Ua=new Map;this.Xa=new Map;this.context.G.addEventListener(g.mA("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.nA("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)})},b5=function(a,b,c,d,e,f,h){a.context.j.Na(b,"click",function(l){a.iF(c,d,e,f||[],h||0,l)});
a.context.j.Na(b,"touchstart",function(){a.yb=!1});
a.context.j.Na(b,"touchmove",function(){a.yb=!0})},A1a=function(a){var b;
return(null==(b=g.Tu(a,g.NH))?0:b.url)?g.Tu(a,g.NH).url:(a=g.Tu(a,g.KH))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},c5=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
ES:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
vE:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},B1a=function(a,b,c){a5.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ka=this.Nb=this.B=this.isInitialized=!1;this.qa=null;this.cards=[];this.ub=this.N=this.Ha=this.D=this.Ra=this.j=null;this.W=[];this.Y=this.J=this.kf=this.Ea=null;this.I=0;this.va=new g.Un(function(){},c.U.bf?4E3:3E3);
g.M(this,this.va);this.gb=new g.Un(function(){});
g.M(this,this.gb);this.ra=new t1a(c,function(e,f,h,l,m,n){b5(d,e,f,h,l,m,n)});
this.V=new g.X({F:"div",L:"iv-drawer",T:{id:"iv-drawer"},S:[{F:"div",L:"iv-drawer-header",T:{"aria-role":"heading"},S:[{F:"span",L:"iv-drawer-header-text"},{F:"button",Ca:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",L:"iv-drawer-content"}]});g.M(this,this.V);this.C=this.V.element;this.eb=new g.EL(this.V,330);g.M(this,this.eb);this.Eb=g.eh("iv-drawer-header-text",this.C);this.u=g.eh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Nb&&d5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Nb=d.B)&&e5(d)});
this.G.addEventListener("videodatachange",this.Qp.bind(this))},C1a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){d5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){e5(a)});
var c=b.headerText;g.th(a.Eb,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ea=g.mz(b.trackingParams);a.J=g.mz(b.closeTrackingParams);a.kf=g.mz(b.iconTrackingParams)},D1a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.R().experiments.fb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.rA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},cm:null,zj:e.trackingParams?g.mz(e.trackingParams):null,kf:f&&f.trackingParams?g.mz(f.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,Tx:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};f5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.rA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,f),sponsored:!1,tracking:c5(f,e,f.command),cm:f.trackingParams?g.mz(f.trackingParams):null,zj:e.trackingParams?g.mz(e.trackingParams):null,kf:l&&l.trackingParams?g.mz(l.trackingParams):null,imageUrl:h5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.rA(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,Tx:null,title:f.title?g.rA(f.title):"",customMessage:f.callToAction?g.rA(f.callToAction):"",url:g.Tu(f.command,g.NH).url?X4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Tu(f.command,g.NH).url}):null,onClickCommand:null};f5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.rA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,tracking:c5(e,f,e.endpoint),cm:e.trackingParams?g.mz(e.trackingParams):null,zj:f.trackingParams?g.mz(f.trackingParams):null,kf:l&&l.trackingParams?g.mz(l.trackingParams):null,channelId:g.Tu(e.endpoint,i5).browseId,customMessage:e.customText?g.rA(e.customText):null,profileImageUrl:h5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.rA(e.channelName):"",metaInfo:[e.subscriberCountText?g.rA(e.subscriberCountText):""],url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Tu(e.endpoint,i5).canonicalBaseUrl?g.Tu(e.endpoint,i5).canonicalBaseUrl:"/channel/"+g.Tu(e.endpoint,i5).browseId}),onClickCommand:null};f5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.rA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,tracking:c5(e,f,e.action),cm:e.trackingParams?g.mz(e.trackingParams):null,zj:f.trackingParams?g.mz(f.trackingParams):null,kf:l&&l.trackingParams?g.mz(l.trackingParams):null,xA:h5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.rA(e.customMessage):null,playlistVideoCount:g.rA(e.playlistVideoCount),title:e.playlistTitle?g.rA(e.playlistTitle):"",metaInfo:[e.channelName?
g.rA(e.channelName):"",e.videoCountText?g.rA(e.videoCountText):""],url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:A1a(e.action)}),onClickCommand:null};f5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.rA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,tracking:c5(e,f,e.action),cm:e.trackingParams?g.mz(e.trackingParams):null,zj:f.trackingParams?g.mz(f.trackingParams):null,kf:l&&l.trackingParams?g.mz(l.trackingParams):null,xA:h5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.rA(e.lengthString):null,customMessage:e.customMessage?g.rA(e.customMessage):null,title:e.videoTitle?g.rA(e.videoTitle):"",metaInfo:[e.channelName?
g.rA(e.channelName):"",e.viewCountText?g.rA(e.viewCountText):""],isLiveNow:!!e.badge,url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:A1a(e.action)}),onClickCommand:null};f5(a,b)}}}}}a.I++},h5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},g5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},F1a=function(a,b){if(b=E1a(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.qh(b.wG),g.Zb(a.cards,b),a.xB(),j5(a)},d5=function(a,b,c){if(!a.B){a.eb.show();
a.Ra=new g.Un(function(){g.bo(a.context.G.getRootNode(),g.iT.IV_DRAWER_OPEN)},0);
a.Ra.start();a.qa=g.sx(a.u,"mousewheel",function(h){a.va.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.tz();d&&a.Ea&&a.J&&g.Bz(d,[a.Ea,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.ZP||(f.ZP=!0,G1a(a.context.logger,f.card.tracking.impression,b)),d&&g.Bz(d,[f.card.cm]);F4(a.G);c&&(a.D=new g.Un(function(){a.Ha=a.N;a.ub.focus()},330),a.D.start())}},e5=function(a){a.B&&(a.eb.hide(),g.tx(a.qa),a.qa=null,g.eo(a.context.G.getRootNode(),g.iT.IV_DRAWER_OPEN),a.B=!1,F4(a.G),a.D&&a.D.stop(),a.D=new g.Un(function(){a.Ha&&(a.Ha.focus(),a.Ha=null)},330),
a.D.start())},I1a=function(a){g.co(a.element,[g.iT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.vN(a.G,a.C,5);H1a(a);a.N=g.eh("ytp-cards-button",a.G.getRootNode());a.ub=g.eh("iv-drawer-close-button",a.C);a.isInitialized=!0},H1a=function(a){var b=g.eh("iv-drawer-close-button",a.C);
a.context.j.Na(b,"click",a.uX,a);a.context.j.Na(a.u,"touchend",function(){a.va.start()});
a.context.j.Na(a.u,"scroll",a.OX,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.ao(a.G.getRootNode(),"ytp-autohide")});
a.W.push(g.Mx("iv-button-shown",a.HZ,a));a.W.push(g.Mx("iv-button-hidden",a.GZ,a));a.W.push(g.Mx("iv-teaser-shown",a.bU,a));a.W.push(g.Mx("iv-teaser-hidden",a.JZ,a));a.W.push(g.Mx("iv-teaser-clicked",a.aU,a))},J1a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.Tu(b.onClickCommand,g.OYa))?void 0:c.targetId)?(a.Y=b,!0):!1},K1a=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.Tu(h[0],g.l_a))?void 0:d.timeRangeStartMillis)||0,a.Y=null,!0}}a.Y=b;return!1},f5=function(a,b){if(!J1a(a,b)||K1a(a,b)){var c=L1a(a,b);
if(c){var d={card:b,wG:c.element,ZP:!1};if(!b.onClickCommand){a.isInitialized||I1a(a);F1a(a,b.id);var e=M1a(a,d);g.hc(a.cards,e,0,d);c.xa(a.u,e);a.xB()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,j5(a),N1a(a,d),d5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&O1a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){O1a(a,d)}),j5(a))}}},L1a=function(a,b){switch(b.type){case "simple":var c=a.ra;
var d=b.displayDomain?{F:"div",L:"iv-card-image-text",Z:b.displayDomain}:void 0;var e=w1a(b);d={F:"div",Ca:["iv-card"],S:[{F:"a",L:"iv-click-target",T:{href:b.url?W4(b.url)||"":""},S:[Z4(b.imageUrl,d),{F:"div",L:"iv-card-content",S:[Y4("h2",void 0,b.title),e]}]}]};d=new g.X(d);$4(c,g.dh("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.ra;d={F:"div",Ca:["iv-card","iv-card-channel"],S:[{F:"a",Ca:["iv-click-target"],T:{href:W4(b.url)||"","data-ytid":b.channelId},S:[Z4(b.profileImageUrl),
{F:"div",L:"iv-card-content",S:[u1a(b),{F:"h2",L:"iv-card-primary-link",Z:b.title},v1a(b)]}]}]};d=new g.X(d);$4(c,g.dh("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.ra;d={F:"div",Ca:["iv-card","iv-card-playlist"],S:[{F:"a",L:"iv-click-target",T:{href:W4(b.url)||""},S:[Z4(b.xA,{F:"div",L:"iv-card-image-overlay",S:[{F:"span",L:"iv-card-playlist-video-count",Z:b.playlistVideoCount}]}),{F:"div",L:"iv-card-content",S:[u1a(b),Y4("h2","iv-card-primary-link",b.title),v1a(b)]}]}]};d=
new g.X(d);$4(c,g.dh("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.ra;var f=!g.Xb(b.offers);d=["iv-card"];e="";var h=w1a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({F:"div",L:"iv-card-offer-price",Z:h.price}),h.merchant&&f.push({F:"div",L:"iv-card-offer-merchant",Z:h.merchant}),h={F:"div",S:f});f=b.url?W4(b.url)||"":"";d={F:"div",Ca:d,T:{tabindex:"0"},S:[{F:"a",Ca:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{F:"div",L:"iv-card-content",S:[b.sponsored?{F:"div",L:"iv-card-sponsored",S:["Sponsored",{F:"div",L:"iv-ad-info-container",S:[{F:"div",L:"iv-ad-info",Z:"{{adInfo}}"},{F:"div",L:"iv-ad-info-icon-container",S:[{F:"div",L:"iv-ad-info-icon"},{F:"div",L:"iv-ad-info-callout"}]}]}]}:"",{F:"a",L:"iv-click-target",T:{href:f},S:[Y4("h2",e,b.title),h]}]}]};d=new g.X(d);e=g.mh("span");g.th(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Qd(e,"adInfo");$4(c,g.dh("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.ra;d=b.videoDuration?{F:"span",L:"iv-card-video-duration",Z:b.videoDuration}:void 0;e=b.isLiveNow?{F:"span",Ca:["yt-badge","yt-badge-live"],Z:"LIVE NOW"}:null;f={F:"div",Ca:["iv-card","iv-card-video"],S:[{F:"a",L:"iv-click-target",T:{href:(null==(h=b.url)?void 0:W4(h))||""},S:[Z4(b.xA,d),{F:"div",L:"iv-card-content",S:[u1a(b),Y4("h2","iv-card-primary-link",b.title),v1a(b),e]}]}]};d=new g.X(f);$4(c,g.dh("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.G.R().experiments.fb("web_rounded_containers")&&g.bo(b.element,"ytp-rounded-info");return b},M1a=function(a,b){if(0===a.cards.length)return 0;
a=g.Vb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},P1a=function(a){return a.j?"productListing"===a.j.card.type:g.Od(a.cards,function(b){return"productListing"===b.card.type})},j5=function(a){g.N(a.G.getRootNode(),"ytp-cards-shopping-active",P1a(a))},O1a=function(a,b){if(!g.ao(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.tz(),d=a.j?a.j.card.kf:a.kf;
c&&d&&g.Cz(c,[d]);a.j=b;j5(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.ow(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.gb.isActive()||((!a.B||!a.va.isActive()&&a.Ka)&&N1a(a,b),a.gb.start(910+b.card.teaserDurationMs))}},N1a=function(a,b){a.V.tb?(b=new K4([0,
a.u.scrollTop],[0,b.wG.offsetTop],600,P0a),a.context.B.Na(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Na(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.TK(a.V,!0),a.u.scrollTop=b.wG.offsetTop,g.TK(a.V,!1))},k5=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},E1a=function(a,b){return g.Ub(a.cards,function(c){return c.card.id===b})},l5=function(a,b,c){a5.call(this,a,b);
this.annotation=c;this.isActive=!1},Q1a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},m5=function(a,b,c){l5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},R1a=function(a,b){var c=void 0===c?0:c;
var d=N0a(b).width;g.Cl(b,d);c=new V0a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,O0a);g.M(a,c);a.context.B.Na(c,"begin",function(){g.Il(b,!0)});
c.play()},U1a=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ca:["iv-branding-context-name"],Z:b.channel_name}),d=a.createElement({F:"div",Ca:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.$O(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.xa(d));var f=a.createElement({F:"div",Ca:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Ca:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Il(h,!1);a.context.U.K("web_rounded_containers")&&g.bo(h,"ytp-rounded-branding-context");var l=a.createElement({F:"div",Ca:["branding-context-container-outer"]});l.appendChild(h);g.wl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.Un(function(){S1a(a,h,l)},500);
g.M(a,a.B);a.context.j.Na(a.element,"mouseover",function(){T1a(a,h,l,f,b.image_height)});
a.context.j.Na(a.element,"mouseout",function(){a.B.start()})}},T1a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Hl(b);a.j||(b.style.width=g.Bl(f.width,!0),c.style.width=g.Bl(f.width,!0));g.wl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.wl(d,"right","1px");a.C=!0;g.Il(b,!0);a.D=new g.Un(function(){g.bo(this.element,"iv-branding-active")},0,a);
a.D.start()}},S1a=function(a,b,c){g.eo(a.element,"iv-branding-active");
a.I=new g.Un(function(){g.Il(b,!1);a.j||(c.style.width=g.Bl(0,!0))},250);
a.I.start();a.C=!1},V1a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.U=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},W1a=function(a,b,c){l5.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.V=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ca:["iv-promo-contents"]});this.D=new g.Un(function(){d.j.setAttribute("aria-hidden","true");g.Il(d.B,!1);g.Il(d.u,!0)},700,this);
g.M(this,this.D)},Y1a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=a.annotation.oe(),f=b.image_url;if(f){var h=a.createElement({F:"div",Ca:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",T:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",L:"iv-promo-video-duration",Z:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",L:"iv-promo-playlist-length",Z:b.playlist_length.toString()}),h.appendChild(f));e&&b5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",L:"iv-promo-txt"}),g.Bg(f,W4(e)),a.j=f):a.j=a.createElement({F:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",S:[{F:"strong",
Z:b.text_line_1}]});var m=a.createElement({F:"p",S:[{F:"span",L:"iv-promo-link",Z:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ca:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ca:["iv-button","iv-promo-button"],S:[{F:"span",L:"iv-button-content",Z:f}]});var p=a.createElement({F:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&b5(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.bo(a.j,
"iv-click-target");e&&b5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",S:[{F:"span",Z:b.text_line_1}]}),m=a.createElement({F:"p",S:[{F:"strong",Z:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ca:["yt-badge","iv-promo-badge-live"],Z:"LIVE NOW"})),g.bo(a.j,"iv-click-target"),e&&b5(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&
a.J.appendChild(p);c=a.createElement({F:"div",L:"iv-promo-actions"});a.u=a.createElement({F:"button",Ca:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Na(a.u,"click",function(q){X1a(a,5E3,q)});
c.appendChild(a.u);g.Il(a.u,!1);a.context.j.Na(a.element,"mouseover",a.IY,a);a.context.j.Na(a.element,"mouseout",a.HY,a);a.context.j.Na(a.element,"touchend",function(q){X1a(a,5E3,q)});
a.B=a.createElement({F:"button",Ca:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Na(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.DY:a.CY,a);c.appendChild(a.B);g.co(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},X1a=function(a,b,c){c.stopPropagation();
Z1a(a);$1a(a,b);a.j.focus()},a2a=function(a){a.isCollapsed||a.N||a.C||(g.bo(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},Z1a=function(a){a.D.stop();
a.isCollapsed&&(g.fo(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Il(a.u,!1),g.Il(a.B,!0))},$1a=function(a,b){a.C||(a.C=g.Ph(function(){b2a(this);
a2a(this)},b,a))},b2a=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},c2a=function(a){this.G=a},G1a=function(a,b,c){b&&(c?n5(a,b.map(function(d){return g.Nn(d,c)})):n5(a,b))},n5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Ow(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},d2a=function(a){g.XN.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new c2a(this.player);this.D=new g.SD(this);this.C=this.fn=null;this.events=new g.SD(this);this.J=this.j=null;this.N=[];g.M(this,this.D);this.D.P(this.player,"onVideoAreaChange",function(){b.X("onVideoAreaChange")});
this.D.P(this.player,"onHideControls",function(){b.X("onHideControls")});
this.D.P(this.player,"onShowControls",function(){b.X("onShowControls")});
this.D.P(this.player,"resize",function(d){b.X("resize",d)});
this.D.P(this.player,"presentingplayerstatechange",function(d){b.X("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.cU,this);this.subscribe("resize",this.tD,this);this.player.R().Y.subscribe("vast_info_card_add",this.nR,this);g.M(this,this.events);this.V=this.createElement({F:"div",L:"video-custom-annotations"});this.u=new g.X({F:"div",Ca:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.u);g.vN(this.player,this.u.element,4);this.u.hide();this.B=new g.X({F:"div",Ca:["ytp-iv-video-content"]});g.M(this,this.B);a=this.createElement({F:"div",L:"video-annotations"});
a.appendChild(this.V);this.B.element.appendChild(a);this.Ct()&&this.load();var c=this.createElement({F:"style"});(g.bh("HEAD")[0]||document.body).appendChild(c);g.ff(this,function(){g.qh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},e2a=function(a){a=a.createElement({F:"div",
Ca:["annotation","annotation-type-custom"]});g.Il(a,!1);return a},f2a=function(a,b){b=!b.isCued()&&!g.W(b,1024);
g.TK(a.u,b);g.TK(a.B,b)},g2a=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(g2a(a,e))}return c},k2a=function(a){var b=a.player.getVideoData();
if(b.Ua){var c=a.player.R().Y.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.ou(h)&&h.responseXML?h.responseXML:null)&&h2a(a,h)}};
g.wv()&&(d.onFinish=i2a(a,d.onFinish));d.postParams={ic_only:"1"};j2a(d,c);g.vu(b.Ua,d)}}},j2a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Ux&&(a.postParams.ic_coll=b.Ux);b.CB&&(a.postParams.ic_xml=b.CB);b.CA&&(a.postParams.ic_track=b.CA)},l2a=function(a){var b=new g.X({F:"div"});
g.Il(b.element,!1);var c=new B1a(a.player,b.element,o5(a));g.M(c,b);b.xa(a.u.element);c.mA();return c},o5=function(a){if(!a.J){var b=new M4(a);
g.M(a,b);var c=new g.Qj(a);g.M(a,c);a.J=new V1a(b,c,a.player.R(),a.player.getVideoData(),a.logger,a.player,a.Me)}return a.J},h2a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.tz();if(e){var f=g.sz();f&&g.xz(void 0,e,f,[g.mz(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=g2a(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=V4(f.type,m2a),p=V4(f.style,n2a),q=k1a(f.data),v=0!==q.length?JSON.parse(q):{};var w=f.action;f=q1a;if(null==w)var y=null;else if(g.Oa(w)){l=[];for(var A=g.r(w),B=A.next();!B.done;B=A.next()){var E=f(B.value);
E&&l.push(E)}y=l}else{var G=f(w);y=G?[G]:[]}e=m&&n?new r1a(m,n,p,y,v):null}else e=null}catch(S){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=e2a(f),I=null;switch(l.type){case "branding":if(f.player.R().Qc)break;f.u.element.appendChild(H);I=new m5(H,o5(f),l);break;case "promotion":g.vN(f.player,H,4),I=new W1a(H,o5(f),l)}I&&I.mA();if(f=I)g.M(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=l2a(a),g.M(a,a.j));if("card"===e.type){c=a.j;var O=e&&e.data&&e.data.card_type;
f=e.data;if(O)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,ES:l.teaser_impression,vE:l.teaser_click},H=f.tracking_params||{},I=null,O){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,cm:H.card?g.mz(H.card):null,zj:H.teaser?g.mz(H.teaser):null,kf:H.icon?g.mz(H.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
cm:H.card?g.mz(H.card):null,zj:H.teaser?g.mz(H.teaser):null,kf:H.icon?g.mz(H.icon):null,xA:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "productListing":f.signin_url&&(I=X4({target:"current",value:f.signin_url}));O=[];for(var L=f.offers||[],P=0;P<L.length;P++)O.push(new x1a(g.Wg(L[P].merchant),
g.Wg(L[P].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,cm:H.card?g.mz(H.card):null,zj:H.teaser?g.mz(H.teaser):null,kf:H.icon?g.mz(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Tx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),t3a:I,s3a:f.signin_title?f.signin_title:void 0,r3a:f.signin_message?f.signin_message:void 0,offers:O,onClickCommand:null};f5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,cm:H.card?g.mz(H.card):
null,zj:H.teaser?g.mz(H.teaser):null,kf:H.icon?g.mz(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Tx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,cm:H.card?g.mz(H.card):null,zj:H.teaser?g.mz(H.teaser):null,kf:H.icon?g.mz(H.icon):null,xA:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},f5(c,e)}}else C1a(a.j,e);c=
!0}}c&&(F4(a.player),a.tD())},o2a=function(a,b){var c=!1;
a.j||(a.j=l2a(a),g.M(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(D1a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.rA(b.headerText):"",g.th(c.Eb,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ea=b.trackingParams?g.mz(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.mz(b.closeButton.infoCardIconRenderer.trackingParams):null,c.kf=b.icon.infoCardIconRenderer.trackingParams?
g.mz(b.icon.infoCardIconRenderer.trackingParams):null,F4(a.player),a.tD())},p2a=function(a,b,c,d,e){if(!a.player.R().Qc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new n1a("openUrl","click",new l1a("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.rA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.rA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.rA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.rA(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.rA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.rA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new r1a(c,"branding","branding",f,d);l=e2a(a);a.u.element.appendChild(l);f=new m5(l,o5(a),f);f.mA();g.M(f,f);a.I[c]=f}},i2a=function(a,b){return function(){var c=
g.Aa.apply(0,arguments);
a.isDisposed()||a.N.push(g.Qn.Fh(function(){b.apply(null,g.t(c))}))}},q2a=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.oN.prototype.ow=g.ba(17,function(a,b){var c=g.nO(this.kb());c&&c.ow(a,b)});
var H4={},I4=null;g.Xa(K4,g.no);g.k=K4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Mc())return!1;J4(this);this.startTime=a=g.Ua();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.pD();this.Oj("play");-1==this.j&&this.Oj("resume");this.j=1;var b=g.Ra(this);b in H4||(H4[b]=this);R0a();S0a(this,a);return!0};
g.k.stop=function(a){J4(this);this.j=0;a&&(this.progress=1);T0a(this,this.progress);this.Oj("stop");this.Iz()};
g.k.pause=function(){this.Mc()&&(J4(this),this.j=-1,this.Oj("pause"))};
g.k.ea=function(){0==this.j||this.stop(!1);this.Oj("destroy");K4.Ke.ea.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.hF=function(){this.Oj("animate")};
g.k.Oj=function(a){this.dispatchEvent(new U0a(a,this))};
g.Xa(U0a,g.hf);g.Xa(L4,K4);L4.prototype.C=function(){};
L4.prototype.hF=function(){this.C();L4.Ke.hF.call(this)};
L4.prototype.Iz=function(){this.C();L4.Ke.Iz.call(this)};
L4.prototype.pD=function(){this.C();L4.Ke.pD.call(this)};
g.Xa(V0a,L4);V0a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var i5=new g.To("browseEndpoint");g.u(M4,g.K);M4.prototype.Na=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.sx(a,b,c);this.j.push(a);return a};
M4.prototype.ZC=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.Koa(a,b,c);this.j.push(a);return a};
M4.prototype.xc=function(a){g.tx(a);g.Zb(this.j,a)};
M4.prototype.ea=function(){g.tx(this.j);this.j.length=0;g.K.prototype.ea.call(this)};g.u(Y0a,g.XN);g.k=Y0a.prototype;g.k.load=function(){g.XN.prototype.load.call(this);if(!P4(this)){var a=g.PBa(this.player.getVideoData());a?(a=X0a(a,Z0a(this)),Q4(this,a,!1)):$0a(this)}};
g.k.unload=function(){Q4(this,null);this.B&&(this.B.abort(),this.B=null);g.XN.prototype.unload.call(this)};
g.k.vg=function(a,b){return P4(this)?"loadCustomEndscreenRenderer"===a?(a=X0a(b,"new"),Q4(this,a),!0):null:null};
g.k.getOptions=function(){return P4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<r2a.length;f++){var h=Math.abs(b.width-r2a[f]);if(-1===e||d>=h)e=f,d=h}d=s2a[e];this.u&&g.wl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Gl(e.element,m,f);g.Cl(e.element,n,p);this.W&&(g.fo(e.element,t2a),256<m||256<f?g.bo(e.element,"ytp-ce-large-round"):96<m||96<f?g.bo(e.element,"ytp-ce-medium-round"):g.bo(e.element,"ytp-ce-small-round"));g.fo(e.element,u2a);m=h.left+h.width/2;h=h.top+l/2;g.bo(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.fo(e.element,s2a);g.bo(e.element,d);(e=g.ch(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.wl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())U4(this,this.endscreen.impressionUrls),(a=g.tz())&&this.endscreen.visualElement&&g.yz(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.bo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.bo(b,"ytp-ce-shown");U4(this,c.impressionUrls);(b=g.tz())&&g.yz(b,c.visualElement);this.player.R().B&&this.player.La("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.eo(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.eo(b,"ytp-ce-shown");this.player.R().B&&this.player.La("endscreenelementhidden",a)}};
g.k.N2=function(a){var b=this;a.target===window&&(new g.Un(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.fo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var r2a=[346,426,470,506,570,640,853,1280,1920],s2a="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),u2a=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],t2a=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var m1a={vka:"current",aFa:"new"};var o1a={CLOSE:"close",AIa:"openUrl",SUBSCRIBE:"subscribe"},p1a={Gfa:"click",CLOSE:"close",Era:"hidden",LNa:"rollOut",MNa:"rollOver",GPa:"shown"};r1a.prototype.oe=function(){var a=s1a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var n2a={wba:"anchored",CT:"branding",CHANNEL:"channel",lka:"cta",Hra:"highlightText",yva:"label",PLAYLIST:"playlist",sLa:"popup",jSa:"speech",SUBSCRIBE:"subscribe",mVa:"title",VIDEO:"video",B0a:"website"},m2a={CT:"branding",Lda:"card",Bma:"drawer",Gra:"highlight",ZAa:"marker",sMa:"promotion",TEXT:"text",m1a:"widget"};g.u(a5,g.K);g.k=a5.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.kA(a,b,{id:c,namespace:"annotations_module"});d&&this.Ua.set(a,d);e&&this.Xa.set(a,e);this.context.G.le([a])};
g.k.mA=function(){this.context.u.subscribe("resize",this.xB,this)};
g.k.iF=function(a,b,c,d,e,f){if(this.yb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.qh(this.element)};
g.k.xB=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=W4(a);if(f){var h=z1a(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.gu(f||"");m&&n&&(n.v||n.list)?e.context.G.Cl(n.v,b,n.list,!1):g.dM(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n5(this.context.logger,c,l,d);y1a(f)||(c=g.tz(),d=b.itct,c&&d&&g.Dz(c,g.mz(d)))}};
g.k.ea=function(){this.Ua.clear();this.Xa.clear();g.K.prototype.ea.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.M(this,a);return a.element};g.u(B1a,a5);g.k=B1a.prototype;g.k.Qp=function(){this.Y&&f5(this,this.Y)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Hl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.xB=function(){var a=this.isAvailable();g.Il(this.element,a);g.N(this.context.G.getRootNode(),g.iT.IV_DRAWER_ENABLED,a);F4(this.G)};
g.k.destroy=function(){this.G.ow(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.Nx(this.W);g.tx(this.qa);this.Ra&&this.Ra.dispose();this.D&&this.D.dispose();a5.prototype.destroy.call(this)};
g.k.uX=function(){if(this.B){n5(this.context.logger,k5(this).tracking.close);var a=g.tz();a&&this.J&&g.Dz(a,this.J);e5(this)}};
g.k.OX=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.HZ=function(){var a=g.tz(),b=k5(this);b=b?b.kf:this.kf;a&&b&&g.Bz(a,[b])};
g.k.GZ=function(){var a=g.tz(),b=k5(this);b=b?b.kf:this.kf;a&&b&&g.Cz(a,[b])};
g.k.bU=function(){var a=k5(this);n5(this.context.logger,a.tracking.ES);var b=g.tz();b&&a&&g.Bz(b,[a.zj,a.kf])};
g.k.JZ=function(){var a=g.tz(),b=k5(this);a&&b&&g.Cz(a,[b.zj])};
g.k.aU=function(a){var b=k5(this),c=g.tz();this.j?a?(a=this.context.logger,n5(a,b.tracking.vE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.zj&&g.Dz(c,b.zj)):(a=this.context.logger,n5(a,b.tracking.vE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.kf&&g.Dz(c,b.kf)):(a=this.context.logger,n5(a,b.tracking.vE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.kf&&g.Dz(c,this.kf))};g.u(l5,a5);l5.prototype.mA=function(){a5.prototype.mA.call(this);Q1a(this)};
l5.prototype.show=function(){a5.prototype.show.call(this);var a=g.tz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Bz(a,[g.mz(b.itct)])};
l5.prototype.hide=function(){a5.prototype.hide.call(this);var a=g.tz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Cz(a,[g.mz(b.itct)])};g.u(m5,l5);
m5.prototype.show=function(){if(!this.isActive){l5.prototype.show.call(this);if(!this.J){g.bo(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ca:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Il(this.u,!1);var b=this.context.U.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Ca:["branding-img-container"]}):this.createElement({F:"button",Ca:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=this.annotation.oe();c&&(b=this.context.U.K("html5_player_branding_button_killswitch")?this.u:b,b5(this,b,c,this.annotation.id,a.session_data));U1a(this,a);this.J=!0}g.Il(this.element,!0);this.isActive=!0;this.u&&R1a(this,this.u)}};
m5.prototype.hide=function(){this.isActive&&(l5.prototype.hide.call(this),g.Il(this.element,!1),this.isActive=!1)};
m5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);l5.prototype.destroy.call(this)};g.u(W1a,l5);g.k=W1a.prototype;g.k.show=function(){this.isActive||(l5.prototype.show.call(this),this.V||(Y1a(this),this.V=!0),g.Il(this.element,!0),g.Ph(function(){g.eo(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,b2a(this),Z1a(this),$1a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.bo(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.iF=function(a,b,c,d,e,f){return this.isCollapsed?!1:l5.prototype.iF.call(this,a,b,c,d,e,f)};
g.k.IY=function(a){this.N=!0;X1a(this,500,a)};
g.k.HY=function(){this.N=!1;a2a(this)};
g.k.CY=function(a){a.stopPropagation();this.hide()};
g.k.DY=function(a){a.stopPropagation();b2a(this);this.isCollapsed=!0;g.bo(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();l5.prototype.destroy.call(this)};g.u(d2a,g.XN);g.k=d2a.prototype;g.k.vg=function(a,b){if(!q2a(this.player.R().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.rXa(b))&&h2a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(F1a(this.j,b),F4(this.player)),!0}return null};
g.k.getOptions=function(){return q2a(this.player.R().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ct=function(){var a=this.player.R(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.vQ||a.Y.get(b.videoId)||g.kI(b)||g.lI(b)?!0:!1};
g.k.tD=function(){if(this.B){var a=this.player.Za().getVideoContentRect(!0);g.Gl(this.B.element,a.width,a.height);g.Cl(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Rj();a=this.j;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.k.cU=function(a){f2a(this,a.state);g.W(a.state,2)&&(this.wi()&&this.Zl()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.ow(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.ou(h)&&h.responseXML?h.responseXML:null)&&(h2a(b,h),g.bo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.XN.prototype.load.call(this);f2a(this,this.player.Ab());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.wv()&&(a=i2a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.R().Y.get(d);f&&j2a(e,f);f=f&&(f.CB||f.Ux);if(!c.Fn||f)c.Ua?this.C=g.vu(c.Ua,e):(this.fn=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.fn));
g.vN(this.player,this.B.element,4);this.tD();(f=g.kI(c))&&o2a(this,f);(f=g.lI(c))&&f.featuredChannel&&p2a(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ua&&(this.fn&&(this.player.removeEventListener("videodatachange",this.fn),this.fn=null),this.C=g.vu(b.Ua,a))};
g.k.unload=function(){this.player.zf("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,F4(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.XN.prototype.unload.call(this);this.B.detach();this.fn&&(this.player.removeEventListener("videodatachange",this.fn),this.fn=null)};
g.k.nR=function(a){a===this.player.getVideoData().videoId&&(this.loaded?k2a(this):this.load())};
g.k.wi=function(){return!!this.j&&this.j.isAvailable()};
g.k.Zl=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.wi();this.j&&(a?c?d5(this.j,c,b):d5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):e5(this.j))};
g.k.ow=function(a,b){this.player.X(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ea=function(){this.player.R().Y.unsubscribe("vast_info_card_add",this.nR,this);g.eo(this.player.getRootNode(),g.iT.IV_DRAWER_OPEN);for(var a=this.N,b=g.Qn,c=0,d=a.length;c<d;c++)b.Mk(a[c]);this.N.length=0;g.XN.prototype.ea.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.M(this,a);return a.element};g.WN("annotations_module",d2a);g.WN("creatorendscreen",Y0a);})(_yt_player);
