(function(g){var window=this;'use strict';var w2a=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},x2a=function(a){return g.fG(a)&&!a.K("web_player_i_see_captions_3_killswitch")},y2a=function(a,b){var c,d,e;
return g.z(function(f){if(1==f.j)return c=a+"|"+b,g.x(f,g.uw(),2);if(3!=f.j){d=f.u;if(!d)throw g.Sv("gct");return g.x(f,g.iH(d),3)}e=f.u;return f.return(e.get("captions",c))})},z2a=function(a,b){var c=new g.mH;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},A2a=function(a,b,c){y2a(a,b).then(function(d){d&&c(d.trackData,new g.mH(d.metadata))})},D2a=function(a){if(!B2a.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(C2a,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},r5=function(){this.segments=[]},E2a=function(a,b){var c=g.jc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Yb(a.segments,c),g.Yb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.hc(a.segments,c,0,b),g.hc(a.segments,c+1,0,b)))},F2a=function(a,b,c,d,e,f){g.K.call(this);
this.policy=a;this.player=b;this.W=c;this.N=d;this.D=e;this.V=f;this.U=this.player.R();this.C=new r5;this.I=-1;this.B=this.u=this.j=null;this.J=new g.Un(this.WP,1E3,this);this.events=new g.SD(this);g.M(this,this.J);g.M(this,this.events);this.events.P(b,"SEEK_COMPLETE",this.Sv);this.Sv();this.WP()},G2a=function(a){return a.j&&a.j.C?a.j.C+a.player.xd()<a.player.getCurrentTime():!1},H2a=function(a,b){var c=g.nD(b,a.policy,{}).oe(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.yu(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.Ixa(e);if(h){e=g.nD(a.u,a.policy,{});a.u.Sj(e,h);H2a(a,a.u);break a}f?a.player.ma("capfail",{status:e.status}):(a.player.ej().To("fcb_r"),h=a.u.j[0].Ia,null!=a.N&&a.I!==h&&(f=a.u.j[0],a.D?a.N(e.response,1E3*(f.startTime+a.player.xd())):a.N(e.responseText,1E3*(f.startTime+a.player.xd())),a.I=h))}a.u=null;a.B=null}}).Xi(function(e){a.u=
null;
a.B=null;var f;a.player.ma("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;E2a(a.C,a.u.j[0].Ia)},s5=function(a,b){g.$N.call(this,b.R());
this.j=a;this.G=b;this.B=null;this.D=!1;this.I=g.hG(this.G.R())&&!this.j.isManifestless},J2a=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.bO(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.x0a.get(e);null==n&&(n=I2a[e]||I2a[e.replace(/-/g,"_")],g.x0a.set(e,n));h=n||h}c.push(new g.mH({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},K2a=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},L2a=function(a,b,c){var d=
[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.bO(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},t5=function(a,b,c,d,e,f,h,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Rd);a.params.Rd&&Object.assign(n,a.params.Rd);Object.assign(n,c.Rd);m.Rd=n;g.X.call(this,{F:"div",L:"caption-window",T:{id:"caption-window-"+a.id,dir:1===m.gh?"rtl":"ltr",tabindex:"0",lang:m.lang},S:[{F:"span",L:"captions-text",T:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.va=!1;this.u=a;this.Ha=this.Ea=null;this.playerWidth=f;this.playerHeight=h;this.I=null;this.maxWidth=.96*f;this.Ua=.96*
h;this.j=m;this.Nb=c;this.W=b;this.C=this.ya("captions-text");this.ub=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Y=e/360*16;!l.fb("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.Y=f/640*16);this.type=0;this.Xa=this.Y*M2a(n);a=new g.Zy(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.fU,this);a.subscribe("dragmove",this.eU,this);a.subscribe("dragend",this.dU,this);this.gb=this.eb=0;b=
"";this.j.windowOpacity&&(a=D2a(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":N2a[this.j.textAlign]};this.ub&&(a["border-radius"]=b?this.Xa/8+"px":"");if(this.B=2===this.u.params.gh||3===this.u.params.gh)b=this.element,c="vertical-rl",1===this.j.MK&&(c="vertical-lr"),g.Cc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.wl(b,"-o-writing-mode",c),g.wl(b,"-webkit-writing-mode",c),g.wl(b,"writing-mode",
c),g.wl(b,"text-orientation","upright"),g.bo(b,"ytp-vertical-caption"),3===this.u.params.gh&&(g.wl(b,"text-orientation",""),g.wl(b,"transform","rotate(180deg)"));g.wl(this.element,a);switch(this.j.Lj){case 0:case 1:case 2:g.bo(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.bo(this.element,"ytp-caption-window-bottom")}},M2a=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},O2a=function(a,b){var c={},d=b.background?b.background:a.j.Rd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Rd.backgroundOpacity;d=D2a(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ub&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Xa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Y*M2a(b)+"px";d=1;e=b.color||a.j.Rd.color;if(b.color||null!=b.textOpacity)e=D2a(e),d=null==b.textOpacity?a.j.Rd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.xG&&(h=e=b.xG);var l=a.Y/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Iu()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Rd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.eZ&&(c.visibility="hidden");1===b.pP&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.lG||g.Qv,3===a.u.params.gh?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.ul||2===b.ul||3===b.ul||4===b.ul||5===b.ul)if(g.lG)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.ul){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},P2a=function(a){a.I=g.mh("SPAN");
g.wl(a.I,{display:"block"});g.bo(a.I,"caption-visual-line");a.C.appendChild(a.I)},Q2a=function(a,b){var c=g.mh("SPAN");
g.wl(c,{display:"inline-block","white-space":"pre-wrap"});g.wl(c,O2a(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.wl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.wl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},R2a=function(a,b,c){a.va=a.va||!!c;
var d={};Object.assign(d,a.j.Rd);Object.assign(d,c||b.j);Object.assign(d,a.Nb.Rd);(c=!a.I)&&P2a(a);for(var e=a.Ea&&a.Ha&&g.Ef(d,a.Ha)?a.Ea:Q2a(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(P2a(a),e=Q2a(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.nh(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.lG||!g.yl(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.yl(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.kf?g.wl(e,m,"1em"):g.wl(e,m,"0.5em")))}a.Ha=d;a.Ea=e;a.D.push(b)},u5=function(a,b,c,d){g.$N.call(this,a);
this.videoData=b;this.audioTrack=c;this.Sa=d;this.C=b.Hx},v5=function(a,b,c,d,e,f,h,l){t5.call(this,a,b,c,d,e,f,h,l);
this.type=1},w5=function(a,b,c,d,e,f,h,l){t5.call(this,a,b,c,d,e,f,h,l);
this.type=2;this.J=[];this.V=this.N=this.Ka=0;this.qa=NaN;this.yb=0;this.Eb=null;this.Ra=new g.Un(this.L1,433,this);g.bo(this.element,"ytp-caption-window-rollup");g.M(this,this.Ra);g.wl(this.element,"overflow","hidden")},S2a=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.MK&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},T2a=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Lo,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.N=d;b=Math;c=b.max;isNaN(a.qa)&&((d=a.j.tp)?(e=g.mh("SPAN"),g.th(e,"\u2013".repeat(d)),g.wl(e,O2a(a,a.j.Rd)),a.C.appendChild(e),a.qa=e.offsetWidth,a.C.removeChild(e)):a.qa=0);d=a.C;a.V=c.call(b,a.qa,a.yb,(a.B?d.offsetHeight:d.offsetWidth)+1)},U2a=function(a,b){T2a(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.N-c;if(c!==a.Ka){var d=0<c&&0===a.Ka;b||isNaN(c)||d||(g.bo(a.element,"ytp-rollup-mode"),g.Vn(a.Ra));g.wl(a.C,"transform",S2a(a,c));a.Ka=c}T2a(a)},x5=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.kA.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},y5=function(a,b,c,d,e){g.kA.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},V2a=function(a){var b="_"+z5++;
return new y5(0,0x8000000000000,0,b,a)},X2a=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Ye){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=W2a(l.textContent,n.textContent,p.textContent,f.textContent,h);return new x5(a,b,e,c,l,d,m)}switch(m.Ye){case 9:case 10:m.ul=1;break;case 11:m.ul=2;break;case 12:m.ul=3;break;case 13:m.ul=4;break;case 14:m.ul=5}return new x5(a,b,e,c,l.textContent||"",d,m)},W2a=function(a,b,c,d,e){var f=g.Iu(),h=
f?g.mh("DIV"):g.mh("RUBY"),l=g.mh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.mh("DIV"):g.mh("RP");a.textContent=b;h.appendChild(a);b=f?g.mh("DIV"):g.mh("RT");b.textContent=c;h.appendChild(b);c=e.Ye;if(10===c||11===c||12===c||13===c||14===c)if(g.wl(b,"text-emphasis-style","filled circle"),g.wl(b,"text-emphasis-color","currentcolor"),g.wl(b,"webkit-text-emphasis","filled circle"),11===e.Ye||13===e.Ye)g.wl(b,"webkit-text-emphasis-position","under left"),g.wl(b,"text-emphasis-position","under left");c=!0;if(4===e.Ye||7===e.Ye||12===e.Ye||
14===e.Ye)g.wl(h,"ruby-position","over"),g.wl(h,"-webkit-ruby-position","before");else if(5===e.Ye||6===e.Ye||11===e.Ye||13===e.Ye)g.wl(h,"ruby-position","under"),g.wl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.mh("DIV"):g.mh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.wl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.wl(f,"display","none"),f=f.nextElementSibling,g.wl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.wl(h.lastElementChild,"display","none"),d?(g.wl(h,"padding-top","0.6em"),g.wl(f,"top","0")):(g.wl(h,"padding-bottom","0.6em"),g.wl(f,"bottom","0")));return h},A5=function(){g.K.apply(this,arguments)},B5=function(a){A5.call(this);
this.C=a;this.pens={};this.N={};this.V={};this.D="_"+z5++;this.J={};this.B=this.j=null;this.I=!0},C5=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},D5=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},E5=function(a,b){a=C5(a,b);
return void 0!==a?a:null},G5=function(a,b){a=a.getAttribute(b);
if(null!=a)return F5.test(a),a},Y2a=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.V[d]:a.C);a=E5(b,"mh");null!=a&&(c.Pv=a);a=E5(b,"ju");null!=a&&(c.textAlign=a);a=E5(b,"pd");null!=a&&(c.gh=a);a=E5(b,"sd");null!=a&&(c.MK=a);a=G5(b,"wfc");null!=a&&(c.windowColor=a);b=C5(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},Z2a=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=E5(b,"ap");null!=a&&(c.Lj=a);a=C5(b,"cc");null!=a&&(c.tp=a);a=C5(b,"ah");null!=a&&(c.Oi=a);a=C5(b,"rc");null!=a&&(c.Lo=a);b=C5(b,"av");null!=b&&(c.vl=b);return c},$2a=function(a,b,c,d){var e={};
Object.assign(e,Z2a(a,b));Object.assign(e,Y2a(a,b));d?g.Ef(e,a.C)?(d=a.D,e=a.C):d="_"+z5++:d=b.getAttribute("id")||"_"+z5++;a=C5(b,"t")+c;b=C5(b,"d")||0x8000000000000;if(2===e.gh||3===e.gh)c=e.Lo,e.Lo=e.tp,e.tp=c;return new y5(a,b,0,d,e)},H5=function(a){A5.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},I5=function(a){a=g.Eg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},a3a=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Lo=a);b=b.ccColCount;void 0!==b&&(f.tp=b);if(2===f.gh||3===f.gh)b=f.Lo,f.Lo=f.tp,f.tp=b;return new y5(c,d,0,e,f)},c3a=function(){this.B=this.time=this.mode=this.u=0;
this.C=new b3a(this);this.D=new b3a(this);this.j=[];this.clear()},e3a=function(a,b,c){if(255===a&&255===b||!a&&!b)return{zr:a,
mp:b,result:0};a=d3a[a];b=d3a[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.mp===d;if(d)return{zr:a,mp:b,result:1}}else if(b&128&&1<=a&&31>=a)return{zr:a,mp:b,result:2};return{zr:a,mp:b,result:3}},g3a=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,f3a(a.C,b,c,d))},h3a=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.r(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?g3a(a,d.MN,d.NN,b):1===d.type&&a.u&496&&f3a(a.D,d.MN,d.NN,b);a.j.length=0},J5=function(){this.type=0},K5=function(){this.state=this.mp=this.zr=0},i3a=function(){this.timestamp=this.j=0},L5=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new J5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new i3a}},M5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var v=q.timestamp;v<e&&(e=v);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),v=p.timestamp,v<=e&&(e=v),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},n3a=function(a,b){switch(a){case 0:return j3a[(b&127)-32];
case 1:return k3a[b&15];case 2:return l3a[b&31];case 3:return m3a[b&31]}return 0},N5=function(a){return a.B[a.row][a.u]},O5=function(a,b,c){2<=b&&1<a.u&&(--a.u,N5(a).j=0);
var d=N5(a);d.timestamp=a.D.time+0;d.j=n3a(b,c);32>a.u&&a.u++},o3a=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},P5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},p3a=function(a){a.row=0<a.j?a.j:1;
a.u=1;P5(a,0,15)},q3a=function(a){this.B=a;
this.D=0;this.style=new J5;this.I=new L5(this.B);this.J=new L5(this.B);this.text=new L5(this.B);this.u=this.I;this.C=this.J;this.j=this.u},r3a=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(M5(d,c),p3a(a.u),p3a(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(M5(d,c),P5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},s3a=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},t3a=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},b3a=function(a){this.j=a;
this.D=0;this.B=new q3a(this.j);this.I=new q3a(this.j);this.u=new K5;this.C=this.B},f3a=function(a,b,c,d){a.u.update();
b=e3a(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.zr;c=b.mp;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&O5(a,0,b),c&96&&O5(a,0,c),0!==b&&0!==c&&3===a.style.type&&M5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.zr=e,b.mp=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;o3a(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));P5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:O5(b.j,0,32);break a;case 48:57===c?(d=b.j,N5(d).j=0,32>d.u&&d.u++):O5(b.j,1,c&15)}break;case 2:c&32&&O5(b.j,2,c&31);break;case 3:c&32&&O5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:s3a(b);
break;case 33:d=b.j;1<d.u&&(--d.u,N5(d).j=0);break;case 36:d=b.j;b=N5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:r3a(b,2,d);break;case 38:r3a(b,3,d);break;case 39:r3a(b,4,d);break;case 40:O5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);p3a(d);t3a(b);break;case 43:t3a(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:M5(a,d)}P5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;M5(a,d);o3a(a,b,b+1,a.j-1);P5(a,a.row,1)}break;case 46:P5(b.C,0,15);break;case 47:M5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,s3a(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},u3a=function(){},Q5=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},R5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},S5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},T5=function(a,b){A5.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new c3a;this.j.u=1<<this.track},w3a=function(a){if("string"===typeof a)return!1;
a=new Q5(a,8,0);return v3a(a)},v3a=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==S5(a))return!1;
a.version=R5(a);if(1<a.version)return!1;R5(a);R5(a);R5(a);return!0},U5=function(){A5.call(this)},x3a=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new x5(b,c,d,e.id,p.nodeValue,f||0<n,g.Bf(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);x3a(a,b,c,d,e,!0,p,q,m)}}},y3a=function(a){var b=a.split(":");
a=0;b=g.r(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},z3a=function(a,b,c,d){d=Object.assign({Pv:0},d);
return new y5(a,b,c,"_"+z5++,d)},V5=function(a,b){g.K.call(this);
this.G=a;this.U=b;this.j=null;this.u=this.G.uv()},F3a=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.u&&b){var f=e,h=A3a(a,b,d),l=[];try{for(var m=g.r(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,v=p.CK;l="string"!==typeof q?l.concat(B3a(a,c,q,v,f)):"WEBVTT"===q.substring(0,6)?l.concat(C3a(a,q,v)):l.concat(D3a(a,c,q,v))}var w=l}catch(y){g.iz(y),a.clear(),w=[]}if(0!==w.length)return w}b=E3a(b);if(!b)return[];try{return"string"!==typeof b?B3a(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?C3a(a,b,d):D3a(a,c,b,d)}catch(y){return g.iz(y),a.clear(),[]}},E3a=function(a){if("string"===
typeof a||w3a(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.pC(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.aC(a)},A3a=function(a,b,c){if("string"===typeof b||w3a(b))return[{trackData:b,
CK:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.xwa(d);if(a.u&&e){var f=g.pwa(e),h=g.qwa(e);e=e.j;f&&e&&a.u.DA(e,f,h)}f=g.yC(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.r(f.entries());for(h=f.next();!h.done;h=f.next())e=g.r(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.aC(e),a.push({trackData:e,CK:c+1E3*h});G3a(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
G3a=function(a,b,c){var d=g.pC(a,0,1836476516),e=9E4;
d&&(e=g.qC(d)||9E4);d=0;var f=g.yC(a,1836019558);f=g.r(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.r(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.pC(a,l.dataOffset,1953653094))&&(l=g.pC(a,l.dataOffset,1952867444))&&(l=g.wC(l)/e*1E3,0===h&&(d=l),b[h].CK=l-d+c||c*h*1E3)}},B3a=function(a,b,c,d,e){if(!w3a(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new T5(e,b));return a.j.u(c,d)},C3a=function(a,b,c){a.j||(a.j=new U5);
a=a.j.u(b,c);.01>Math.random()&&g.jz(Error("Deprecated subtitles format in web player: WebVTT"));return a},D3a=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new H5(H3a(b))),a.j.u(c,d)}catch(f){return g.iz(f),[]}var e=g.rXa(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new B5(H3a(b),a.U)),a.j.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},H3a=function(a){var b=
{};
if(a=g.pH(a))b.lang=a,g.IYa.test(a)&&(b.gh=1);return b},W5=function(a){g.XN.call(this,a);
var b=this;this.G=a;this.U=this.G.R();this.videoData=this.G.getVideoData();this.gb=this.G.Za();this.B={Rd:{}};this.D={Rd:{}};this.ra=[];this.N={};this.Ha={};this.W=!1;this.Nb=g.sI(this.videoData);this.Xa=g.vHa(this.videoData,this.G);this.Eb=!!this.videoData.captionTracks.length;this.kc=!!this.videoData.yc;this.Ka="3"===this.U.controlsType;this.u=this.I=this.J=this.Ea=this.eb=null;this.Ra=new V5(this.G,this.U);this.j=null;this.Y=new g.SD(this);this.Ua=new g.X({F:"div",L:"ytp-caption-window-container",
T:{id:"ytp-caption-window-container"}});var c=null,d=g.Ko("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.yo(d));this.storage=c;var e;this.yb=!(null==(e=a.Od())||!e.uA());this.C=I3a(this);this.V=!this.C&&this.Ka&&this.yb&&this.Xa;g.M(this,this.Ra);this.C?this.va=this.qa=null:(this.qa=new g.Sn(this.fL,void 0,this),g.M(this,this.qa),this.va=new g.Un(this.y3,2E3,this),g.M(this,this.va));g.M(this,this.Y);this.U.K("caption_window_container_killswitch")||g.vN(this.player,this.Ua.element,4);
g.M(this,this.Ua);this.C||this.Y.P(a,"resize",this.hL);(this.ub=!g.Oy()&&!this.G.isFullscreen()&&!this.C&&!this.V&&!this.U.K("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.Y.P(a,"resize",this.N0);this.Y.P(a,"onPlaybackAudioChange",this.W_);this.Y.P(a,g.mA("captions"),function(f){b.onCueRangeEnter(f)});
this.Y.P(a,g.nA("captions"),function(f){b.onCueRangeExit(f)});
J3a(this,K3a(this)||{})},O3a=function(a){if(1===a.U.eb||1===a.videoData.sx||"alwayson"===g.bI(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.U.eb){var c;g.jG(a.U)?c=L3a(a):c=M3a(a,"module-enabled");if(null!=c)return!!c}c=w2a(a.player.getAudioTrack(),x2a(a.U));var d=g.bI(a.videoData,"yt:cc");if(void 0===N3a(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===g.bI(a.videoData,"yt:cc")},X5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},N3a=function(a){var b=void 0,c=g.kv(g.jv.getInstance(),65);
if(g.jG(a.U)&&null!=c){if(null!=L3a(a))return!1;b=!c}return b},P3a=function(a){var b;
a.Nb?b=new u5(a.U,a.videoData,a.player.getAudioTrack(),a.player):a.Xa?b=new s5(a.videoData.j,a.player):a.Eb?b=new g.aO(a.U,a.videoData,a.player.getAudioTrack()):b=new g.cO(a.U,a.videoData.yc,a.videoData.videoId,g.UBa(a.videoData),a.videoData.Fl);return b},Z5=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.kc?!1:a.Eb?!1:!0);b=g.YN(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.U.captionsLanguagePreference,g.bI(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.pH(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||Y5(a)}return null},Y5=function(a){return a.I&&a.I.j},$5=function(a){var b=Y5(a);
return!!b&&a.j===b},Q3a=function(a){var b=w2a(a.player.getAudioTrack(),x2a(a.U)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=Z5(a,a.W):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&X5(a)?c=Y5(a):N3a(a)||a.W||O3a(a)?c=Z5(a,a.W):X5(a)&&(c=Y5(a));if(a.C||a.V){var d=g.YN(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.mh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.nH(f));h.setAttribute("srclang",g.pH(f));h.setAttribute("id",f.toString());a.V||h.setAttribute("src",a.u.hs(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.G.Od();c.Nx(b);c=c.rf();
a.yb&&a.Y.P(c.textTracks,"change",a.A2)}else!a.j&&c&&a6(a,c),a.player.La("onCaptionsTrackListChanged"),a.player.La("onApiChange")},R3a=function(a,b){var c=a.G.Od().rf().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},a6=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.W=c,a.W&&(g.jG(a.U)?b6(a,!!b):c6(a,"module-enabled",!!b)));a.j=b;X5(a)&&(a.j=Y5(a));a.load()},T3a=function(a,b){if(b instanceof y5){var c=a.N[b.id];
c&&c.u!==b&&(c.dispose(),delete a.N[b.id],c=null);c||(c=S3a(a,b))&&(a.N[b.id]=c)}else c=b.windowId,a.Ha[c]||(a.Ha[c]=[]),a.Ha[c].push(b)},U3a=function(a,b){a.U.K("caption_window_container_killswitch")?g.vN(a.player,b,4):a.Ua.element.appendChild(b)},S3a=function(a,b){var c=a.gb.getVideoContentRect(!0).height,d=a.gb.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.pH(a.j):null;e&&g.IYa.test(e)&&(b.params.gh=1);e=a.gb.getPlayerSize();a.U.K("web_player_caption_stickiness_for_glive_killswitch")||"google-live"!==a.U.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.Pv?b.params.Pv:1<b.j.length?1:0){case 1:return new v5(b,a.B,a.D,d,c,e.width,e.height,a.U.experiments);case 2:return new w5(b,a.B,a.D,d,c,e.width,e.height,a.U.experiments);default:return new t5(b,a.B,a.D,d,c,e.width,e.height,a.U.experiments)}},
J3a=function(a,b,c){c=void 0===c?!1:c;
var d=d6.Rd;a.B={};Object.assign(a.B,d6);a.B.Rd={};Object.assign(a.B.Rd,d);a.D={Rd:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;F5.test(f);e.Rd.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;F5.test(f);e.Rd.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||d6.windowColor;F5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Rd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Rd.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Rd;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Rd.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=d6.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Rd.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Rd.fontFamily=f;a.loaded&&a.hL();c&&(a.U.K("web_player_local_storage_for_captions_setting_killswitch")?c6(a,"display-settings",b):g.Hz("yt-player-caption-display-settings",b,2592E3))},W3a=function(a,b,c){b&&!a.J?(b=V2a({gh:0,
lang:"en"}),a.J=[b,new x5(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.le(a.J)):!b&&a.J&&(V3a(a,a.J),a.J=null)},V3a=function(a,b){a.player.eh(b);
b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.Zb(a.ra,c.value);g.Tn(a.qa)},M3a=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},c6=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},b6=function(a,b){a.G.isInline()||g.Hz("yt-player-sticky-caption",b,2592E3)},L3a=function(a){if(!a.G.isInline())return g.Iz("yt-player-sticky-caption")},K3a=function(a){return a.U.K("web_player_local_storage_for_captions_setting_killswitch")?M3a(a,"display-settings"):g.Iz("yt-player-caption-display-settings")},I3a=function(a){var b,c=!(null==(b=a.G.Od())||!b.tA());
return a.Ka&&c&&!a.Xa};
g.uS.prototype.Cy=g.ba(34,function(a){var b=2;this.Ha.has(a)?b=0:g.GKa(this,a)&&(b=1);return b});
g.mV.prototype.Cy=g.ba(33,function(a){return this.kd.Cy(a)});
g.uS.prototype.DA=g.ba(32,function(a,b,c){this.va.set(a,{PB:b,Lx:c})});
g.mV.prototype.DA=g.ba(31,function(a,b,c){this.kd.DA(a,b,c)});
g.qO.prototype.Mu=g.ba(29,function(){for(var a=g.ch(document,"track",void 0,this.j),b=0;b<a.length;b++)g.qh(a[b])});
g.eS.prototype.Mu=g.ba(28,function(){this.mediaElement.Mu()});
g.qO.prototype.uA=g.ba(27,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.eS.prototype.uA=g.ba(26,function(){return this.mediaElement.uA()});
g.qO.prototype.tA=g.ba(25,function(){return!!this.j.textTracks});
g.eS.prototype.tA=g.ba(24,function(){return this.mediaElement.tA()});
g.qO.prototype.Nx=g.ba(23,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.eS.prototype.Nx=g.ba(22,function(a){this.mediaElement.Nx(a)});
g.$N.prototype.JJ=g.ba(21,function(){return!1});
g.$N.prototype.Zp=g.ba(20,function(){});
g.aO.prototype.Zp=g.ba(19,function(a,b,c){var d=this;this.isDisposed();b=this.hs(a,b);this.Vo();this.j=g.vu(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.cO.prototype.Zp=g.ba(18,function(a,b,c){var d=this;this.isDisposed();b=this.hs(a,b);this.Vo();this.j=g.vu(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.bV.prototype.Oy=g.ba(8,function(){return this.J});
g.EX.prototype.Oy=g.ba(7,function(){var a;return(null==(a=g.jN(this))?void 0:a.uv())||null});
g.oN.prototype.uv=g.ba(6,function(){return this.app.Oy()});
g.eX.prototype.uv=g.ba(5,function(){var a;return(null==(a=this.Ga)?void 0:a.Oy())||null});
var C2a=/#(.)(.)(.)/,B2a=/^#(?:[0-9a-f]{3}){1,2}$/i,I2a={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",
bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",
chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",
goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",
ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",
kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",
lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",
mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",
ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};r5.prototype.contains=function(a){a=g.jc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
r5.prototype.length=function(){return this.segments.length/2};
g.u(F2a,g.K);g.k=F2a.prototype;g.k.ea=function(){g.K.prototype.ea.call(this);this.B&&this.B.cancel()};
g.k.Sv=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.xd();var b=this.j;this.j=g.Pb(this.W.qm(a).j);b!==this.j&&this.V&&this.V()};
g.k.reset=function(){this.C=new r5;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.WP=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.ep(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.lx(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai){var c=this.player.uv();if(c){var d=a.j[0].Ia;if(b=c.mm(a.j[0].B,d,a.j[0].j.info.id,3))if(c=c.Cy(d),0===c)b&&(a.B=new g.DB(b));else if(2===c){this.J.start();G2a(this)&&this.seekTo(this.player.getCurrentTime());return}}}a.j[0].duration?(this.C.contains(a.j[0].Ia)||
H2a(this,a),this.j=g.Pb(a.j)):!this.U.K("force_caption_seek_for_live_killswitch")&&G2a(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.u(s5,g.$N);g.k=s5.prototype;g.k.Zp=function(a,b,c){var d=this;this.Vo();b=K2a(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?L2a(this,b,"386"):L2a(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.tHa(this.U);this.B=new F2a(f,this.G,b,function(h,l){c(h,a,l,e)},this.I||g.BD(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.JJ=function(){var a=this.D;this.D=!1;return a};
g.k.Lv=function(a){var b=this.I?[new g.mH({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.mH({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?J2a(this,"386"):J2a(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.ZN(this.u,c.value);a()};
g.k.Vo=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.hs=function(){return""};
var F5=/^#(?:[0-9a-f]{3}){1,2}$/i;var N2a=["left","right","center","justify"];g.u(t5,g.X);g.k=t5.prototype;g.k.fU=function(a,b){var c=g.Fl(this.element,this.element.parentElement);this.eb=a-c.x;this.gb=b-c.y;g.bo(this.element,"ytp-dragging")};
g.k.eU=function(a,b){var c=g.Hl(this.element);a=a-this.eb-.02*this.playerWidth;var d=b-this.gb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Eg(e,0,2));var f=(d+c.height/2)/this.Ua*3;f=Math.floor(g.Eg(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Eg(a,0,1);c=(d+f/2*c.height)/this.Ua;c=100*g.Eg(c,0,1);this.u.params.Lj=b;this.u.params.vl=c;this.u.params.Oi=a;this.u.params.isDefault=!1;this.j.Lj=b;this.j.vl=c;this.j.Oi=a;this.j.isDefault=!1;this.W.Lj=b;this.W.vl=c;this.W.Oi=
a;this.W.isDefault=!1;this.ZR()};
g.k.dU=function(){g.eo(this.element,"ytp-dragging")};
g.k.ZR=function(){this.xw(this.D)};
g.k.getType=function(){return this.type};
g.k.xw=function(a){var b=Math.min(this.IO(),this.maxWidth),c=this.HO(),d="";3===this.u.params.gh&&(d="rotate(180deg)");g.wl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.jG(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Oi+2;d=this.j.Lj;switch(d){case 0:case 3:case 6:(b=this.j.Rd.fontSizeIncrement)&&0<b&&2!==this.j.gh&&3!==
this.j.gh&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.vl+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.wl(this.element,
a)};
g.k.jG=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.va||this.D.length>b)b=0,this.va=!1,this.D=[],this.I=this.Ha=this.Ea=null,g.oh(this.C);for(;b<a.length;b++)R2a(this,a[b])};
g.k.IO=function(){return 0};
g.k.HO=function(){return 0};
g.k.toString=function(){return g.X.prototype.toString.call(this)};g.u(u5,g.$N);u5.prototype.Zp=function(a,b,c){A2a(this.videoData.videoId,a.vssId,c)};
u5.prototype.Lv=function(a){if(this.audioTrack)for(var b=g.r(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.ZN(this.u,c.value);a()};g.u(v5,t5);v5.prototype.jG=function(a){var b=this.u.j;t5.prototype.jG.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,X3a);var e=c.j;var f=d}R2a(this,c,d)}};
var X3a={eZ:!0};g.u(w5,t5);g.k=w5.prototype;g.k.ZR=function(){g.Wn(this.Ra)};
g.k.L1=function(){g.eo(this.element,"ytp-rollup-mode");this.xw(this.Eb,!0)};
g.k.HO=function(){return this.B?this.V:this.N};
g.k.IO=function(){return this.B?this.N:this.V};
g.k.xw=function(a,b){this.Eb=a;if(this.u.params.Lo){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.yb=this.V;this.N=this.V=0;t5.prototype.xw.call(this,a);U2a(this,b)}t5.prototype.xw.call(this,a)};g.u(x5,g.kA);x5.prototype.toString=function(){return g.kA.prototype.toString.call(this)};g.u(y5,g.kA);y5.prototype.toString=function(){return g.kA.prototype.toString.call(this)};
var z5=0;g.u(A5,g.K);A5.prototype.u=function(){return[]};
A5.prototype.reset=function(){};g.u(B5,A5);B5.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
B5.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.r(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.r(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=D5(a,"b");
null!=l&&(h.bold=l);l=D5(a,"i");null!=l&&(h.italic=l);l=D5(a,"u");null!=l&&(h.underline=l);l=E5(a,"et");null!=l&&(h.charEdgeStyle=l);l=E5(a,"of");null!=l&&(h.offset=l);l=G5(a,"bc");null!=l&&(h.background=l);l=G5(a,"ec");null!=l&&(h.xG=l);l=G5(a,"fc");null!=l&&(h.color=l);l=E5(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=C5(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=C5(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=C5(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=E5(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Ye=10<l?l-1:l);a=E5(a,"hg");null!=a&&(h.pP=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.V[c]=Y2a(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=Z2a(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.r(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=$2a(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!D5(a,"a");l=(C5(a,"t")||0)+l;var m=C5(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var v=0;v<q.length;v++){var w=q[v],y=void 0;0<v&&(h=!0);var A=void 0;1===w.nodeType&&(A=w);if(A&&"s"===A.tagName){if((w=(w=A.getAttribute("p"))?this.pens[w]:null)&&w.Ye&&(1===w.Ye?(w=q.slice(v,v+
4),4===w.length&&(y=X2a(l,m,f,h,n,w,this.pens),v+=3)):y=X2a(l,m,f,h,n,[A],this.pens)),!y){var B=A;y=l;A=m;w=f;var E=h,G=n,H=B.textContent?B.textContent:"",I=B.getAttribute("p");I=I?this.pens[I]:null;B=C5(B,"t")||0;y=new x5(y+B,A-B,G,w,H,E,I)}}else y=new x5(l,m,n,f,w.textContent||"",h,p);c.push(y);this.B=y}if(0<c.length)for(c[0].windowId===this.D&&(this.j=$2a(this,a,b,!0),d.push(this.j)),a=g.r(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Y3a=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(H5,A5);H5.prototype.reset=function(){this.B.clear()};
H5.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.r(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.xG=I5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=I5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=I5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Ye=10<h?h-1:h,f.ul=Y3a.get(f.Ye));e.hgHorizGroup&&(f.pP=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.r(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Pv=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.gh=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.MK=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=I5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.r(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.Oi=e.ahHorPos),void 0!==e.apPoint&&(f.Lj=e.apPoint),void 0!==e.avVerPos&&(f.vl=e.avVerPos),void 0!==e.ccCols&&(f.tp=e.ccCols),void 0!==e.rcRows&&(f.Lo=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.r(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=a3a(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+z5++,h=a3a(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var v=p[l],w=v.utf8;if(w){var y=v.tOffsetMs||0,A=null;v.pPenId&&(A=this.j.get(v.pPenId));if(2===(null!=h.params.Pv?h.params.Pv:1<h.j.length?1:0)&&m&&"\n"===w)continue;if(v=A&&1===A.Ye)if(v=l,v+3>=p.length||!p[v+1].pPenId||!p[v+2].pPenId||!p[v+3].pPenId)v=!1;else{var B=p[v+1].pPenId;(B=this.j.get(B))&&B.Ye&&2===B.Ye?(B=p[v+2].pPenId,B=this.j.get(B),!B||!B.Ye||3>B.Ye?v=!1:(B=p[v+3].pPenId,v=(B=this.j.get(B))&&
B.Ye&&2===B.Ye?!0:!1)):v=!1}if(v){y=p[l+1].utf8;v=p[l+3].utf8;B=p[l+2].utf8;var E=this.j.get(p[l+2].pPenId);w=W2a(w,y,B,v,E);m=new x5(d,e,n,f,w,m,A);l+=3}else m=new x5(d+y,e-y,n,h.id,w,m,A||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};c3a.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
c3a.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var d3a=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];J5.prototype.set=function(a){this.type=a};
J5.prototype.get=function(){return this.type};
K5.prototype.clear=function(){this.state=0};
K5.prototype.update=function(){this.state=2===this.state?1:0};
K5.prototype.isValid=function(){return 0!==this.state};
K5.prototype.matches=function(a,b){return this.isValid()&&a===this.zr&&b===this.mp};
i3a.prototype.reset=function(){this.timestamp=this.j=0};
L5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
L5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
L5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var j3a=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],k3a=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],l3a=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],m3a=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];q3a.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
b3a.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};u3a.prototype.C=function(){};g.u(Q5,u3a);Q5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+z5++;c=c/1E3-this.I;d=d/1E3-this.I;a=new y5(c,d-c,5,f,{textAlign:0,Lj:0,Oi:2.5*b,vl:5.33*a});e=new x5(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.u(T5,A5);T5.prototype.u=function(a){a=new Q5(a,a.byteLength,this.B);if(v3a(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=S5(a)*(1E3/45):1===a.version&&(a.B=4294967296*S5(a)+S5(a)),a.D=R5(a);0<a.D;a.D--){var b=R5(a),c=R5(a),d=R5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,MN:c,NN:d,order:b.j.length}))}h3a(this.j,a);return a.u}return[]};
T5.prototype.reset=function(){this.j.clear()};g.u(U5,A5);
U5.prototype.u=function(a,b){var c=[];a=a.split(Z3a);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!$3a.test(e)){var h=a4a.exec(e);if(h&&4<=h.length){var l=y3a(h[1]),m=y3a(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var v=null,w="";n=g.r(n);for(var y=n.next();!y.done;y=n.next())if(y=y.value.split(":"),2===y.length){var A=y[1];switch(y[0]){case "line":y=A.split(",");y[0].endsWith("%")&&(p=y[0],h.vl=Number.parseInt(p,10),2===y.length&&(q=y[1].trim()));break;case "position":y=
A.split(",");v=y[0];h.Oi=Number.parseInt(v,10);2===y.length&&(w=y[1].trim());break;case "align":switch(A){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!v)switch(h.textAlign){case 0:h.Oi=0;break;case 1:h.Oi=100;break;case 2:h.Oi=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Lj=q}e=e.substring(a4a.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=z3a(l,m,5,w),m=new x5(l,m,5,f.id,h,!1,g.Bf(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(b4a),1===q.length?(h=5,w=z3a(l,m,h,w)):(p=h=6,w=Object.assign({tp:32},w),w=new y5(l,m,p,"_"+z5++,w)),c.push(w),p=l,v=0;v<q.length;v++)n=q[v],0===v%2?(y=g.rXa("<html>"+n+"</html>"),y.getElementsByTagName("parsererror").length?
(A=y.createElement("span"),A.appendChild(y.createTextNode(n))):A=y.firstChild,x3a(this,p,m-(p-l),h,w,0<v,A,e,c)):p=y3a(n)+f}a4a.lastIndex=0}}return c};
var $3a=/^NOTE/,Z3a=/(?:\r\n|\r|\n){2,}/,a4a=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),b4a=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.gS.MC(U5,{u:"wvppt"});g.u(V5,g.K);V5.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
V5.prototype.reset=function(){this.j&&this.j.reset()};
V5.prototype.ea=function(){g.K.prototype.ea.call(this);this.clear()};var d6={windowColor:"#080808",windowOpacity:0,textAlign:2,Lj:7,Oi:50,vl:100,isDefault:!0,Rd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(W5,g.XN);g.k=W5.prototype;g.k.ea=function(){if(this.C||this.V){var a=this.G.Od();a&&!a.isDisposed()&&a.Mu()}else W3a(this,!1);g.XN.prototype.ea.call(this)};
g.k.Ct=function(){if(this.Ka)return this.C||this.V;var a=w2a(this.player.getAudioTrack(),x2a(this.U));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?X5(this):N3a(this)||X5(this)?!0:O3a(this)};
g.k.load=function(){var a=this;g.XN.prototype.load.call(this);var b=!this.U.K("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.j&&(this.Ra.clear(),this.C?R3a(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Zp(this.j,"json3",function(c,d,e,f){if(c){a.u.JJ()&&(a.ra=[],a.G.zf("captions"),g.Tn(a.qa),a.Ra.reset());c=F3a(a.Ra,c,d,e,f);a.player.le(c,void 0,a.Xa);if(!(!a.W||a.V||$5(a)||g.XF(a.U)||g.OF(a.U))){g.Xn(a.va);c=V2a({Lj:0,Oi:5,vl:5,Lo:2,
textAlign:0,gh:0,lang:"en"});a.Ea=[c];e=["Click "," for settings"];a.eb||(f=new g.QK(g.gL()),g.M(a,f),a.eb=f.element);f=c.end-c.start;var h=g.nH(a.j);h&&a.Ea.push(new x5(c.start,f,0,c.id,h));a.Ea.push(new x5(c.start,f,0,c.id,e[0]),new x5(c.start,f,0,c.id,a.eb,!0),new x5(c.start,f,0,c.id,e[1],!0));a.player.le(a.Ea);g.Vn(a.va)}!a.W||a.V||$5(a)||(g.jG(a.U)?b6(a,!0):c6(a,"module-enabled",!0),a.I&&(a.I.C=a.j),a.player.Mt());var l;null==(l=a.G.Fc())||l.ma("cc",{kind:d.kind});a.W=!1}}),!b||this.C||this.V||
$5(this)||this.player.La("captionschanged",g.oH(this.j))),b||(this.j&&!$5(this)?this.player.La("captionschanged",g.oH(this.j)):this.player.La("onCaptionsTrackListChanged"))):(this.u=P3a(this),g.M(this,this.u),this.u.Lv(function(){Q3a(a)}))};
g.k.unload=function(){this.C&&this.j?R3a(this,!1):(this.va&&g.Xn(this.va),this.player.zf("captions"),this.ra=[],this.u&&this.u.Vo(),this.Ra.clear(),this.J&&this.player.le(this.J),this.hL());g.XN.prototype.unload.call(this);this.player.Mt();this.player.La("captionschanged",{})};
g.k.create=function(){this.Ct()&&this.load()};
g.k.A2=function(){for(var a=this.G.Od().rf().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.YN(this.u.u,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.j:null)!==b&&a6(this,b,!0)};
g.k.r5=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.ra.push(a);g.Tn(this.qa)};
g.k.onCueRangeExit=function(a){g.Zb(this.ra,a);this.u instanceof s5&&this.u.I&&this.player.eh([a]);g.Tn(this.qa)};
g.k.getCaptionWindowContainerId=function(){return this.Ua.element.id};
g.k.y3=function(){V3a(this,this.Ea);this.Ea=null};
g.k.fL=function(){var a=this;if(!this.ub||!this.C){this.qa.stop();g.Fca(this.Ha);this.ra.sort(g.lA);var b=this.ra;if(this.J){var c=g.vm(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.r(b);for(c=b.next();!c.done;c=b.next())T3a(this,c.value);b={};c=g.r(Object.entries(this.N));for(var d=c.next();!d.done;b={Nq:b.Nq,Dk:b.Dk},d=c.next()){var e=g.r(d.value);d=e.next().value;e=e.next().value;b.Nq=d;b.Dk=e;this.Ha[b.Nq]?(b.Dk.element.parentNode||(b.Dk instanceof w5||b.Dk instanceof v5||g.uf(this.N,function(f){return function(h,l){l!==f.Nq&&h.u.params.Lj===f.Dk.u.params.Lj&&h.u.params.Oi===f.Dk.u.params.Oi&&h.u.params.vl===f.Dk.u.params.vl&&(h.dispose(),delete a.N[l]);
return l===f.Nq}}(b),this),U3a(this,b.Dk.element)),b.Dk.xw(this.Ha[b.Nq])):(b.Dk.dispose(),delete this.N[b.Nq])}}};
g.k.E3=function(){J3a(this,{},!0);this.U.K("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.La("captionssettingschanged")};
g.k.yY=function(){var a=d6.Rd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:d6.windowColor,windowOpacity:d6.windowOpacity};var b=K3a(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.hT=function(a,b){var c={};Object.assign(c,K3a(this));Object.assign(c,a);J3a(this,c,b);this.player.La("captionssettingschanged")};
g.k.hL=function(){!this.C&&this.loaded&&(g.of(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.fL())};
g.k.vg=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Eg(b,-2,4);this.hT({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&a6(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.U.B&&(g.jG(this.U)?b6(this,!!b):c6(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Pa(b))break;if(g.Bf(b)){a6(this,null,!0);break}a=g.YN(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?z2a(e,b.translationLanguage):e)}!c||c===this.j&&this.loaded||(b=g.rya(),a=g.pH(c),b.length&&a===b[b.length-1]||(b.push(a),g.Hz("yt-player-caption-language-preferences",b)),a6(this,c,!0))}else return this.loaded&&this.j&&!$5(this)?g.oH(this.j):{};return"";case "tracklist":return this.u?g.Ok(g.YN(this.u.u,!(!b||!b.includeAsr)),function(f){return g.oH(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||W3a(this,!!b);break;case "sampleSubtitlesCustomized":this.C||W3a(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.U.B&&a.push("stickyLoading");return a};
g.k.KH=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.U.K("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.pH(a));return{cc:b}}return{}};
g.k.W4=function(){this.loaded&&this.j&&!$5(this)?(g.jG(this.U)?b6(this,!1):c6(this,"module-enabled",!1),this.unload(),X5(this,!0)&&a6(this,Y5(this),!1)):this.LS()};
g.k.LS=function(){this.loaded&&this.j&&!$5(this)||a6(this,$5(this)||!this.j?Z5(this,!0):this.j,!0)};
g.k.W_=function(){var a=$5(this);X5(this,a)?a6(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Ct()&&(a?a6(this,Z5(this),!1):this.load()))};
g.k.N0=function(){var a=this.G.Od();a&&!a.isDisposed()&&a.Mu();this.G.isFullscreen()?(this.C=this.Ka=!0,this.loaded&&Q3a(this)):(this.Ka="3"===this.U.controlsType,this.C=I3a(this));a6(this,this.j)};
g.gS.MC(W5,{fL:"smucd"});g.WN("captions",W5);})(_yt_player);
